import "../styles/globals.scss";
import "bootstrap/dist/css/bootstrap.min.css";
import Head from "next/head";
import { Container } from "react-bootstrap";
import { NavbarForImmo } from "../components/navbar.jsx";

function MyApp({ Component, pageProps }) {
  return (
    <div>
      <Head>
        <title>Immo Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavbarForImmo />
      <Container className="main-container container-fluid">
        <Component {...pageProps} />
      </Container>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Slawa
        </a>
      </footer>
    </div>
  );
}

export default MyApp;
